using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public static class Texts 
{
    public static string t1 = "Este cuaderno está dedicado a mi exploración sobre la “Torre de Arena”, el lugar de exilio de aquellos que se rebelaron a la deidad superior durante las guerras santas, tal y como se recoge en los textos sagrados. He dedicado años de trabajo a encontrar la forma de llegar al lugar de destierro de los exiliados y poder hacer un estudio de lo que en los textos sagrados se relata.\r\n\nTras mucho tiempo, por fin he localizado la forma de entrada a la torre de arena. Al parecer, a pesar de su pésimo estado, el portal de llegada sigue funcionando. Como era de esperar, no permite realizar el viaje de vuelta, por lo que me toca ingeniármelas para volver.\r\n\nSegún los textos sagrados, este portal fue creado por la deidad superior al mismo tiempo que la Torre de Arena, para ser usado como método de envío de los castigados al exilio en la guerra.\r\n\nA partir de aquí no me queda más que seguir explorando la torre para encontrar todos sus puntos importantes, así como encontrar una forma de salir de aquí con vida.";

    public static string t2 = "He sido capaz de localizar el árbol del perdón. Se trata del árbol que las deidades supremas dejaron a los exiliados por misericordia cuándo en el segundo castigo separaron el oasis del resto de la “Torre de Arena”, impidiendo a los exiliados disfrutar de sus frutos mientras los tenían a simple vista. La importancia de este árbol es que era la única fuente de alimento que los exiliados podían utilizar.\r\n\nBajo las raíces del árbol parece haber alguna serie de conductos, pero creo que será mejor no entrar, pues la tierra qué forma estas cavidades parece no ser muy sólida y se podría desmoronar en cualquier momento. El buen desarrollo del árbol, así como la baja solidez de la tierra, me da la impresión de que podría haber agua en el subsuelo, lo cual explicaría que el árbol que sea capaz de brotar y sobrevivir en medio de esta zona desértica.\r\n\nA primera vista creo que el árbol se encuentra en el centro de la torre, por lo que me podrá servir de orientación en mis exploraciones. De momento, basándome en la posición del Sol, Creo que la montaña qué puedo ver desde aquí queda al noroeste y el portal al este. Espero que cuando consiga tener la isla más explorada pueda hacer un mapa con la distribución de los diferentes lugares.";

    public static string t3 = "Mi siguiente destino fue la cima de la montaña, para poder tener una vista de toda la torre desde el alto y dibujar un mapa, aunque parecía una brillante idea ha resultado de poca ayuda, la gran cantidad de arena en el aire hace que sea casi imposible ver a largas distancias. Pero no todo son malas noticias, en un momento en el que el viento pareció amansar un poco he sido capaz de vislumbrar algo que parecía ser el oasis al norte del portal. Además, aunque no estoy seguro, me pareció ver algún tipo de construcción al sur, debería explorarlo más tarde.\r\n\nLa montaña es más alta de lo que me esperaba, aunque no me sorprende, al fin y al cabo fue el motivo del segundo castigo. Según los textos sagrados, los exiliados intentaron usar sus alas desde lo alto de la montaña con la intención de llegar volando al plano superior, lo cual enfureció a la deidad superior, la cual los castigó arrebatándole sus alas y quitándoles sus principales fuentes de alimento, el oasis, tal y como expliqué en la nota anterior.";

    public static string t4 = "Para mi sorpresa, mientras descendía la montaña me he encontrado con un lugar que no aparecía en los textos sagrados, aunque lo que hay en su interior es de suma importancia. Se trata de una cueva en la ladera de la susodicha montaña, en su interior la falta de luz y las temperaturas bajas contrastan con lo que ocurre en el exterior, por lo que pudo haber sido uno de los refugios más importantes para los exiliados. También de suma importancia es que en su interior hay una cascada con agua, lo que explica de dónde sacaban el agua los exiliados tras la pérdida del oasis.\r\n\nA pesar de que este emplazamiento no aparece en los textos sagrados, hay algo de él que sí lo hace, los cristales rosas que en su interior se encuentran. Estos cristales fueron usados por los exiliados para la creación de lo que causaría su tercer y último castigo, las plumas negras, también conocidas como las falsas plumas.\r\n\nTeniendo en cuenta que acabo de corroborar la existencia de estos cristales, mis expectativas sobre encontrar el lugar donde estas plumas fueron creadas ha aumentado, espero encontrarlo y poder descubrir alguna información.";

    public static string t5 = "Tras dirigirme al sur me he encontrado con un templo, supongo que se tratará de lo que los exiliados llamaron “el Templo de la Pluma”. Según los textos sagrados se trata del lugar donde los exiliados crearon las plumas negras. Se trata de una construcción simple hecha con la piedra de los alrededores. Tras un vistazo rápido al interior, creo que lo usaban para hacer algún tipo de ritual, al menos en la zona en la que puedo acceder. Al fondo de la sala principal se encuentra una puerta que no consigo abrir, creo que detrás podría haber algo relacionado con la creación de las plumas negras, pero soy incapaz de entrar.\r\n\nMis deducciones son que este templo lo construyeron originalmente como refugio contra el sol y el calor cuando perdieron el oasis, pero que con el tiempo se volvió un lugar de culto y reflexión para los exiliados.\r\n\nAunque queda parte por explorar en este templo, he decidido centrarme primero en visitar toda la zona, por lo que actualmente me dirigiré hacia el noreste, donde me pareció ver el oasis desde lo alto de la montaña. Cuando haya acabado de explorar toda la torre regresaré al templo para volver a intentar abrir la puerta.";

    public static string t6 = "Tal y como había visto desde lo alto de la montaña, el oasis se encuentra al noreste de la torre. Para llegar hasta allí he necesitado el uso de mis alas, pues hay un vacío entre este y el resto del terreno. Al fin y al cabo, como pone en los textos sagrados, el oasis fue separado del resto de la torre como castigo a los exiliados por intentar volver al plano superior desde la montaña usando sus alas. Al haberle quitado las alas por ese mismo motivo, el espacio que yo he podido superar resultaba imposible de saltar para los exiliados, lo que suponía que no solo pasarían hambre por falta del suministro que el oasis le sustentaba, sino que además tendrían aquello que más querían en un lugar en el que podrían verlo, pero no alcanzarlo, dando lugar a que fuese un recordatorio del castigo por toda la eternidad.\r\n\nEl oasis cuenta con una variedad de árboles bastante grande, con suficiente producción para alimentar a un grupo bastante grande de individuos. Asimismo, también cuenta con agua, útil tanto para consumo como para el buen desarrollo de los árboles que aquí existen. \r\n\nUna vez encontrado el oasis, la mayoría de la torre ya ha sido explorada, por lo que me dirigiré al templo bordeando la torre, para centrarme en intentar hallar la forma de abrir la puerta que allí se encuentra.";

    public static string t7 = "De camino al templo me encontré con el altar de comunicación, lugar donde se aplicó el castigo final a todos los exiliados por el sacrilegio de la creación de las plumas negras. Según los textos sagrados, este castigo consistió en la eliminación de las falsas plumas y que todos los exiliados fueran privados de su memoria, para ser enviados al plano inferior sin tener conocimiento alguno de su pasado. De esta forma, los exiliados vivirían en ese plano como si siempre hubiera sido así y con completo desconocimiento de la existencia del plano superior.\r\n\nTras examinar el altar parece que este, a pesar de su deterioro, podría seguir funcionando. En su centro parece haber unas ranuras que se podrían activar de alguna forma, posiblemente utilizando las plumas. Creo que esta es la opción más factible para encontrar una salida de la torre, por lo que cuando acabe de explorar toda la zona intentaré encontrar la forma de activar el altar.";

    public static string t8 = "De vuelta en el templo me dediqué a entender el mecanismo que controla la puerta, el cual se trata de un sistema de seguridad que permite abrir la puerta con una combinación de botones específica. Tras conseguir descifrar esa combinación, lo que había detrás de la puerta me ha dejado muy sorprendido, contaba con encontrar alguna información sobre cómo crearon las plumas negras, pero al parecer los exiliados fueron capaces de esconder alguna de estas falsas plumas. He decidido dejarla en su sitio de momento mientras el estudio, pues no sé qué podría pasar si la manipulo.\r\n\nAprovechando que estoy al refugio de este templo, creo que tengo la información suficiente como para dibujar un pequeño mapa de la torre. Creo que será de gran ayuda en caso de que alguien tenga que volver a este inhóspito lugar.\r\n\nTras haber realizado el mapa, los descubrimientos hechos en este templo me han hecho pensar que podría haber más plumas escondidas en alguna zona de la torre. Por eso he decidido volver a explorar aquellos sitios en los que ya he estado, a ver si encuentro algún otro hallazgo igual de importante.";

}
